---
- import_tasks: privilege.yml
  tags: privilege
  when: home_privilege_mode
  become: yes

- import_tasks: common.yml
  tags: common
  become: no

- import_tasks: dotemacs.yml
  tags: dotemacs
  become: no
