---
- name: python-apt should be installed
  apt:
    name: "python-apt"
    state: present
    update_cache: yes

- name: required packages should be installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "cmigemo"
    - "tree"
